
type JsonArray = list[JsonValue]
type JsonObject = dict[str, JsonValue]
type JsonValue = JsonObject | JsonArray | str | int | float | bool | None

class _ProgramWithInput:
    def first(self) -> JsonValue: ...
    def all(self) -> list[JsonValue]: ...
    def text(self) -> str: ...

class _Program:
    def input_value(self, value: object) -> _ProgramWithInput: ...
    def input_text(self, text: str) -> _ProgramWithInput: ...
    def input_values(self, *values: object) -> _ProgramWithInput: ...
    @property
    def program_string(self) -> str: ...

def compile(expression: str) -> _Program: ...
