from typing import Any

class _ProgramWithInput:
    def first(self) -> Any: ...
    def all(self) -> list[Any]: ...
    def text(self) -> str: ...

class _Program:
    def input_value(self, value: object) -> _ProgramWithInput: ...
    def input_text(self, text: str) -> _ProgramWithInput: ...
    def input_values(self, *values: object) -> _ProgramWithInput: ...
    @property
    def program_string(self) -> str: ...

def compile(expression: str) -> _Program: ...
